### ISSUE TITLE
[NFR] Support both {{}} and {%%} formats to support entire Django template family

### ISSUE THREAD

**Issue by dschissler** [smhg/gettext-swig#1]
It appears that {{ }} always uses paranthesis and that {% %} doesn't. They are intended for different uses but that so far appears to be the only constant as different engines use them for different functionality.  By supporting both of these formats the Swig parser can be used across the entire line of Django family templates (and there are several varieties).

**Comment by dschissler** [comment]
@smhg Just a minor nitpick but I was directly told by a Swig developer some weeks ago that this form is not a "filter" but a "function".  In Swigland a filter must be piped a value to transform.  That was the discussion that lead us to where we are at now.

**Comment by smhg** [comment]
Thanks for the explanation. Did the new version work for you?

**Comment by dschissler** [comment]
I haven't tried the latest one yet.  I'm working on creating a webpack loader for nunjucks.  I like it better than Swig.  Same syntax though.
