### ISSUE TITLE
Consider loosening the spaces match from '{{ +' to '{{ {0,3}'

### ISSUE THREAD

**Issue by dschissler** [smhg/gettext-swig#3]
Its valid to have no spaces after the `{{`.  I set it at up to a maximum of 3 spaces just because it could help if someone quickly pasted it in while testing.  I was having issues with getting it to run until I browsed at the source.

```javascript
  this.expressionPattern = new RegExp([
//    '{{ +',
    '{{ {0,3}',
    '(' + Object.keys(keywordSpec).map(escapeRegExp).join('|') + ')',
    '\\(',
    '([\\s\\S]*?)',
    '\\)',
    ' {0,3}}}'
//    ' +}}'
    ].join(''), 'g');
}
```

Sorry, I'm too lazy for a pull request plus I figure that you need to reversion npm anyways if you like it.  Personally, I need this.

**Comment by smhg** [comment]
Spaces are now optional with the `*` quantifier.
